1. Load the dataset into dataframe.
2. perform a "Left Join" on the TransactionID column to attach the train_identity data to the train_transaction data.

In [2]:
import pandas as pd


transaction_path = '../raw_dataset/train_transaction.csv'
identity_path = '../raw_dataset/train_identity.csv'

print("Loading datasets ...")
train_transaction = pd.read_csv(transaction_path)
train_identity = pd.read_csv(identity_path)

print("Merging datasets on TransactionID...")
train = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')

# Print the dimensions of our new combined dataset
print(f"Merged dataset shape: {train.shape}")

# Display the first 5 rows to verify it worked
train.head()

Loading datasets ...
Merging datasets on TransactionID...
Merged dataset shape: (590540, 434)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [ ]:
%load_ext autoreload
%autoreload 2
from utils.dataset_inspector import generate_visual_reports

generate_visual_reports(train, target_col='isFraud', output_dir='summary/tabular_statistics')

print(f"Dataset Shape: {train.shape}")
display(train.head())
display(train.tail())

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Generating graphical tables and charts...
✅ All summaries saved to 'summary/'!
Dataset Shape: (590540, 434)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
590535,3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
from utils.verifier import run_full_verification

run_full_verification(train, sample_size=1000, output_dir='summary/verification_results/')

Sampling 1000 random rows for verification...
Running verification across 403 numerical features. This may take a minute...
Generating formatted PDF report...

✅ Verification Complete!
Total Checks: 3224 | Passed: 3224 | Failed: 0
Full report saved to: summary/verification_results/scratch_vs_pandas_verification.pdf

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from matplotlib.backends.backend_pdf import PdfPages
from scratch_implementation.custom_imputer import ScratchImputer

print("Analyzing all 434 columns and applying imputation rules... (This may take 1-3 minutes)")

# 1. Initialize and run the imputer on the FULL dataset
imputer = ScratchImputer(missing_threshold=0.70, skew_threshold=1.0)
train_clean, strategy_report = imputer.fit_transform(train)

# 2. Before and After Details
print("\n--- BEFORE VS AFTER MISSING VALUE TREATMENT ---")
print(f"BEFORE:")
print(f"  Shape: {train.shape}")
print(f"  Total Missing Cells: {train.isnull().sum().sum():,}")
print(f"\nAFTER:")
print(f"  Shape: {train_clean.shape}")
print(f"  Total Missing Cells: {train_clean.isnull().sum().sum():,}")

# --- FIX: Proper Directory Routing and PDF Generation ---

# 3. Save Tabular Summary as PDF
tabular_dir = 'summary/tabular_statistics/'
os.makedirs(tabular_dir, exist_ok=True)
pdf_path = os.path.join(tabular_dir, 'imputation_reasoning_report.pdf')

print("\nGenerating paginated PDF report...")
with PdfPages(pdf_path) as pdf:
    rows_per_page = 35 # Slightly fewer rows to ensure the 'Reason' text fits
    chunks = [strategy_report[i:i + rows_per_page] for i in range(0, len(strategy_report), rows_per_page)]
    
    for idx, chunk in enumerate(chunks):
        fig, ax = plt.subplots(figsize=(14, len(chunk) * 0.4 + 1)) # Wider figure for text
        ax.axis('tight')
        ax.axis('off')
        
        table = ax.table(cellText=chunk.values, colLabels=chunk.columns, loc='center', cellLoc='left')
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1.2, 1.5)
        
        # Style the header row
        for (row, col), cell in table.get_celld().items():
            if row == 0:
                cell.set_text_props(weight='bold', color='white')
                cell.set_facecolor('#4c72b0')
            elif col == 2: # Give the 'Reason' column more breathing room
                cell.set_width(0.6) 
                
        plt.title(f"Imputation Reasoning Report (Page {idx + 1} of {len(chunks)})", weight='bold', pad=20)
        pdf.savefig(fig, bbox_inches='tight')
        plt.close()

print(f"✅ Full tabular reasoning report saved to: {pdf_path}")

# 4. Save Pie Chart to Visualization Folder
vis_dir = 'summary/visualization/'
os.makedirs(vis_dir, exist_ok=True)
pie_chart_path = os.path.join(vis_dir, 'imputation_strategies_pie_chart.png')

plt.figure(figsize=(9, 9))
strategy_counts = strategy_report['Strategy'].value_counts()

colors = ['#ff9999', '#66b3ff', '#99ff99', '#ffcc99', '#c2c2f0']
plt.pie(strategy_counts, labels=strategy_counts.index, autopct='%1.1f%%', 
        startangle=140, colors=colors[:len(strategy_counts)], 
        wedgeprops={'edgecolor': 'black', 'linewidth': 1})

plt.title('Distribution of Imputation Strategies Across All Features', weight='bold', size=14)

plt.savefig(pie_chart_path, bbox_inches='tight', dpi=300)
plt.close()
print(f"✅ Pie chart visualization saved to: {pie_chart_path}\n")

Analyzing all 434 columns and applying imputation rules... (This may take 1-3 minutes)

--- BEFORE VS AFTER MISSING VALUE TREATMENT ---
BEFORE:
  Shape: (590540, 434)
  Total Missing Cells: 115,523,073

AFTER:
  Shape: (590540, 226)
  Total Missing Cells: 0

Generating paginated PDF report...
✅ Full tabular reasoning report saved to: summary/tabular_statistics/imputation_reasoning_report.pdf
✅ Pie chart visualization saved to: summary/visualization/imputation_strategies_pie_chart.png

In [11]:
train = train_clean

In [13]:
train.shape

(590540, 226)

In [14]:
# Calculate the total number of rows
total_rows = len(train)

# Find any column where the number of unique values exactly matches the number of rows
unique_cols = [col for col in train.columns if train[col].nunique() == total_rows]

print(f"Columns with 100% unique values: {unique_cols}")

Columns with 100% unique values: ['TransactionID']

In [16]:
# Import the duplicate handler
from utils.duplicate_handler import handle_duplicates

# Run the function. It handles the logic and creates both reports automatically.
train = handle_duplicates(train, id_column='TransactionID')

Checking for duplicates using scratch hash implementation...
Generating hash signatures for all rows...
Found and dropped 0 duplicate rows.
✅ PDF summary saved to summary/tabular_statistics/task_d1_duplicate_summary.pdf
✅ Bar chart saved to summary/visualization/task_d1_duplicate_chart.png